services:
  api_service:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    hostname: api_service
    container_name: api_service
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHON_ENV=${PYTHON_ENV}
      - PORT=${PORT}
      - AUTH_USERNAME=${AUTH_USERNAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
    # env_file:
    #   - src/api/.env
    volumes:
      - ./src/api:/home/api
    networks:
      - claimsprocessing_net

  ai_workflow:
    build:
      context: ./src/ai_workflow
      dockerfile: Dockerfile
    hostname: ai_workflow
    container_name: ai_workflow
    restart: unless-stopped
    ports:
      - "50051:50051"
    environment:
      - PYTHON_ENV=${PYTHON_ENV}
      - PORT=${PORT}
      - AUTH_USERNAME=${AUTH_USERNAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - PROJECT_ID=${PROJECT_ID}
      - REGION=${REGION}
      - STAGING_BUCKET=${STAGING_BUCKET}
      - APP_BACKEND_API=${APP_BACKEND_API}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
    # env_file:
    #   - src/ai_workflow/.env
    volumes:
      - ./src/ai_workflow:/home/ai_workflow
    networks:
      - claimsprocessing_net

networks:
  claimsprocessing_net: 
