# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/protos/claims_processing.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'src/protos/claims_processing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"src/protos/claims_processing.proto\x12\x11\x63laims_processing\x1a\x1bgoogle/protobuf/empty.proto\" \n\rClaimsRequest\x12\x0f\n\x07\x63laimId\x18\x01 \x01(\t\"\x14\n\x12HealthCheckRequest\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xbe\x01\n\x10\x43laimsProcessing\x12J\n\x0cProcessClaim\x12 .claims_processing.ClaimsRequest\x1a\x16.google.protobuf.Empty\"\x00\x12^\n\x0bHealthCheck\x12%.claims_processing.HealthCheckRequest\x1a&.claims_processing.HealthCheckResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.protos.claims_processing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLAIMSREQUEST']._serialized_start=86
  _globals['_CLAIMSREQUEST']._serialized_end=118
  _globals['_HEALTHCHECKREQUEST']._serialized_start=120
  _globals['_HEALTHCHECKREQUEST']._serialized_end=140
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=142
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=179
  _globals['_CLAIMSPROCESSING']._serialized_start=182
  _globals['_CLAIMSPROCESSING']._serialized_end=372
# @@protoc_insertion_point(module_scope)
