# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"w\n\x12LocalMarketRequest\x12\x13\n\x0bsearchTerms\x18\x01 \x01(\t\x12\x14\n\x0ctargetMarket\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x15\n\rloginRequired\x18\x05 \x01(\x08\"4\n\x0e\x41nalysisResult\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x12\n\npriceRange\x18\x02 \x01(\t\">\n\x13LocalMarketResponse\x12\'\n\x0e\x61nalysisResult\x18\x01 \x03(\x0b\x32\x0f.AnalysisResult\"\r\n\x0bHomeRequest\"z\n\x0cHomeResponse\x12\x17\n\x0f\x61pplicationName\x18\x01 \x01(\t\x12\x18\n\x10\x61pplicationOwner\x18\x02 \x01(\t\x12\x1b\n\x13\x61pplicationEngineer\x18\x03 \x01(\t\x12\x1a\n\x12\x61pplicationVersion\x18\x04 \x01(\t\"\x14\n\x12HealthCheckRequest\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xaf\x01\n\x11\x41utomationService\x12\x39\n\x0cMarketSearch\x12\x13.LocalMarketRequest\x1a\x14.LocalMarketResponse\x12#\n\x04Home\x12\x0c.HomeRequest\x1a\r.HomeResponse\x12:\n\x0bHealthCheck\x12\x13.HealthCheckRequest\x1a\x14.HealthCheckResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCALMARKETREQUEST']._serialized_start=17
  _globals['_LOCALMARKETREQUEST']._serialized_end=136
  _globals['_ANALYSISRESULT']._serialized_start=138
  _globals['_ANALYSISRESULT']._serialized_end=190
  _globals['_LOCALMARKETRESPONSE']._serialized_start=192
  _globals['_LOCALMARKETRESPONSE']._serialized_end=254
  _globals['_HOMEREQUEST']._serialized_start=256
  _globals['_HOMEREQUEST']._serialized_end=269
  _globals['_HOMERESPONSE']._serialized_start=271
  _globals['_HOMERESPONSE']._serialized_end=393
  _globals['_HEALTHCHECKREQUEST']._serialized_start=395
  _globals['_HEALTHCHECKREQUEST']._serialized_end=415
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=417
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=454
  _globals['_AUTOMATIONSERVICE']._serialized_start=457
  _globals['_AUTOMATIONSERVICE']._serialized_end=632
# @@protoc_insertion_point(module_scope)
